url: https://www.krddy.com

title: 凯瑞达

keywords: 张力控制器,纠偏控制器,超声波纠偏,张力检测器,跟线纠偏

description: 张力控制器、纠偏控制器、超声波纠偏、张力检测器、跟线纠偏专业自主研发生产销售企业凯瑞达KRD为国内企业提供专业优质的纠偏卷材控制设备。

enurl: http://en.krddy.com

address: 广东省佛山市顺德区容桂镇天富来国际工业城五期8座101号

tel1: 0757-22681566

tel2: 13902564312

sale-tel: 13702626541

fax: 0757-29280639

email: krd@krd.so

qq: 1964506925

weixin: 13702626541

exclude:
  - README.md
  - style.css
